var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/english/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1q8p21y._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0tej5c5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_180tlel.js")
R.c("server/chunks/ssr/[root-of-the-server]__10ldt1g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0r5yz5t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_app_english_loading_tsx_19empkd._.js")
R.c("server/chunks/ssr/_next-internal_server_app_english_page_actions_0-0pfqp.js")
R.m(92615)
module.exports=R.m(92615).exports
