// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/english" | "/english/cloze" | "/english/exam" | "/english/history" | "/english/listening" | "/english/listening/[testId]" | "/english/listening/result/[testId]" | "/english/matching" | "/english/reading" | "/english/reading/[articleId]" | "/english/real-exams" | "/english/translation" | "/english/vocab" | "/english/writing" | "/login" | "/projects" | "/projects/[projectId]/analysis" | "/projects/[projectId]/diagnostic/report" | "/projects/[projectId]/diagnostic/take" | "/projects/[projectId]/errors" | "/projects/[projectId]/exam" | "/projects/[projectId]/materials/[materialId]/review" | "/projects/[projectId]/materials/upload" | "/projects/[projectId]/overview" | "/projects/[projectId]/plan" | "/projects/[projectId]/points" | "/projects/[projectId]/points/[pointId]" | "/projects/[projectId]/practice" | "/projects/new" | "/register" | "/subjects" | "/subjects/[subject]" | "/subjects/[subject]/[section]"
type AppRouteHandlerRoutes = "/api/english/articles" | "/api/english/articles/[id]" | "/api/english/cloze/generate" | "/api/english/exam/generate" | "/api/english/exam/score" | "/api/english/import-link" | "/api/english/listening" | "/api/english/listening/sets" | "/api/english/reading/analyze" | "/api/english/reading/explain" | "/api/english/reading/generate" | "/api/english/reading/submit" | "/api/english/refresh" | "/api/english/word-definition" | "/api/english/writing" | "/api/materials/upload" | "/api/projects" | "/api/projects/[id]" | "/api/projects/[id]/dashboard" | "/api/projects/[id]/diagnostic/generate" | "/api/projects/[id]/diagnostic/submit" | "/api/projects/[id]/errors" | "/api/projects/[id]/errors/[errorId]" | "/api/projects/[id]/exam-points/generate" | "/api/projects/[id]/exam/generate" | "/api/projects/[id]/exam/submit" | "/api/projects/[id]/plan/generate" | "/api/projects/[id]/plan/tasks/[taskId]" | "/api/projects/[id]/plan/today" | "/api/projects/[id]/practice/generate" | "/api/projects/[id]/practice/submit"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/english/articles": {}
  "/api/english/articles/[id]": { "id": string; }
  "/api/english/cloze/generate": {}
  "/api/english/exam/generate": {}
  "/api/english/exam/score": {}
  "/api/english/import-link": {}
  "/api/english/listening": {}
  "/api/english/listening/sets": {}
  "/api/english/reading/analyze": {}
  "/api/english/reading/explain": {}
  "/api/english/reading/generate": {}
  "/api/english/reading/submit": {}
  "/api/english/refresh": {}
  "/api/english/word-definition": {}
  "/api/english/writing": {}
  "/api/materials/upload": {}
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/projects/[id]/dashboard": { "id": string; }
  "/api/projects/[id]/diagnostic/generate": { "id": string; }
  "/api/projects/[id]/diagnostic/submit": { "id": string; }
  "/api/projects/[id]/errors": { "id": string; }
  "/api/projects/[id]/errors/[errorId]": { "id": string; "errorId": string; }
  "/api/projects/[id]/exam-points/generate": { "id": string; }
  "/api/projects/[id]/exam/generate": { "id": string; }
  "/api/projects/[id]/exam/submit": { "id": string; }
  "/api/projects/[id]/plan/generate": { "id": string; }
  "/api/projects/[id]/plan/tasks/[taskId]": { "id": string; "taskId": string; }
  "/api/projects/[id]/plan/today": { "id": string; }
  "/api/projects/[id]/practice/generate": { "id": string; }
  "/api/projects/[id]/practice/submit": { "id": string; }
  "/english": {}
  "/english/cloze": {}
  "/english/exam": {}
  "/english/history": {}
  "/english/listening": {}
  "/english/listening/[testId]": { "testId": string; }
  "/english/listening/result/[testId]": { "testId": string; }
  "/english/matching": {}
  "/english/reading": {}
  "/english/reading/[articleId]": { "articleId": string; }
  "/english/real-exams": {}
  "/english/translation": {}
  "/english/vocab": {}
  "/english/writing": {}
  "/login": {}
  "/projects": {}
  "/projects/[projectId]/analysis": { "projectId": string; }
  "/projects/[projectId]/diagnostic/report": { "projectId": string; }
  "/projects/[projectId]/diagnostic/take": { "projectId": string; }
  "/projects/[projectId]/errors": { "projectId": string; }
  "/projects/[projectId]/exam": { "projectId": string; }
  "/projects/[projectId]/materials/[materialId]/review": { "projectId": string; "materialId": string; }
  "/projects/[projectId]/materials/upload": { "projectId": string; }
  "/projects/[projectId]/overview": { "projectId": string; }
  "/projects/[projectId]/plan": { "projectId": string; }
  "/projects/[projectId]/points": { "projectId": string; }
  "/projects/[projectId]/points/[pointId]": { "projectId": string; "pointId": string; }
  "/projects/[projectId]/practice": { "projectId": string; }
  "/projects/new": {}
  "/register": {}
  "/subjects": {}
  "/subjects/[subject]": { "subject": string; }
  "/subjects/[subject]/[section]": { "subject": string; "section": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
