-- FinalSprint V1 数据库初始化
-- 全部复制 → Supabase SQL Editor → 执行

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "User" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "email" TEXT UNIQUE NOT NULL, "name" TEXT, "avatarUrl" TEXT, "quotaUsed" INTEGER DEFAULT 0, "quotaLimit" INTEGER DEFAULT 300, "createdAt" TIMESTAMP(3) DEFAULT NOW(), "updatedAt" TIMESTAMP(3) DEFAULT NOW());

CREATE TABLE IF NOT EXISTS "Project" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "userId" TEXT NOT NULL REFERENCES "User"("id"), "subjectName" TEXT NOT NULL, "examDate" TIMESTAMP(3) NOT NULL, "targetScore" INTEGER NOT NULL, "currentLevel" TEXT NOT NULL DEFAULT 'weak', "dailyMinutes" INTEGER NOT NULL DEFAULT 60, "goalType" TEXT DEFAULT 'pass', "status" TEXT DEFAULT 'active', "predictedMin" INTEGER, "predictedMax" INTEGER, "createdAt" TIMESTAMP(3) DEFAULT NOW(), "updatedAt" TIMESTAMP(3) DEFAULT NOW());

CREATE TABLE IF NOT EXISTS "ExamScope" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "projectId" TEXT UNIQUE NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE, "sourceType" TEXT NOT NULL DEFAULT 'manual_input', "title" TEXT NOT NULL, "chapterTree" JSONB, "overallCoverage" DOUBLE PRECISION, "pointCoverageMap" JSONB, "createdAt" TIMESTAMP(3) DEFAULT NOW());

CREATE TABLE IF NOT EXISTS "SubjectModule" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "projectId" TEXT NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE, "parentId" TEXT REFERENCES "SubjectModule"("id"), "title" TEXT NOT NULL, "description" TEXT, "orderIndex" INTEGER DEFAULT 0, "estimatedScoreValue" DOUBLE PRECISION, "priorityLevel" INTEGER, "masteryStatus" TEXT DEFAULT 'unknown', "createdAt" TIMESTAMP(3) DEFAULT NOW());

CREATE TABLE IF NOT EXISTS "ExamPoint" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "projectId" TEXT NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE, "moduleId" TEXT REFERENCES "SubjectModule"("id"), "title" TEXT NOT NULL, "summary" TEXT, "estimatedScoreMin" DOUBLE PRECISION, "estimatedScoreMax" DOUBLE PRECISION, "hitRate" DOUBLE PRECISION, "avgStudyMinutes" INTEGER, "roiScore" DOUBLE PRECISION, "targetTier" TEXT, "importanceTier" TEXT, "formulas" JSONB, "commonPatterns" JSONB, "solvingTemplate" JSONB, "traps" JSONB, "sourceEvidence" JSONB, "masteryStatus" TEXT DEFAULT 'unknown', "confidenceScore" INTEGER DEFAULT 0, "createdAt" TIMESTAMP(3) DEFAULT NOW(), "updatedAt" TIMESTAMP(3) DEFAULT NOW());

CREATE TABLE IF NOT EXISTS "Material" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "projectId" TEXT NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE, "title" TEXT NOT NULL, "resourceType" TEXT DEFAULT 'pdf', "sourceUrl" TEXT, "storagePath" TEXT, "rawText" TEXT, "parseStatus" TEXT DEFAULT 'pending', "extractedText" TEXT, "extractionJson" JSONB, "sourceMeta" JSONB, "parsedTranscript" JSONB, "compressedNotes" JSONB, "createdAt" TIMESTAMP(3) DEFAULT NOW(), "updatedAt" TIMESTAMP(3) DEFAULT NOW());

CREATE TABLE IF NOT EXISTS "MaterialExamPointMap" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "materialId" TEXT NOT NULL REFERENCES "Material"("id") ON DELETE CASCADE, "examPointId" TEXT NOT NULL REFERENCES "ExamPoint"("id") ON DELETE CASCADE, "confidence" DOUBLE PRECISION, "sourceChunk" TEXT, "createdAt" TIMESTAMP(3) DEFAULT NOW(), UNIQUE("materialId", "examPointId"));

CREATE TABLE IF NOT EXISTS "PracticeQuestion" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "projectId" TEXT NOT NULL, "examPointId" TEXT NOT NULL REFERENCES "ExamPoint"("id") ON DELETE CASCADE, "type" TEXT NOT NULL, "difficulty" INTEGER NOT NULL DEFAULT 2, "source" TEXT NOT NULL DEFAULT 'generated', "stem" TEXT NOT NULL, "options" JSONB, "answer" JSONB NOT NULL, "explanation" JSONB, "scoreValue" INTEGER DEFAULT 5, "createdAt" TIMESTAMP(3) DEFAULT NOW());

CREATE TABLE IF NOT EXISTS "QuestionAttempt" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "userId" TEXT NOT NULL REFERENCES "User"("id"), "projectId" TEXT NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE, "questionId" TEXT NOT NULL REFERENCES "PracticeQuestion"("id"), "sessionId" TEXT REFERENCES "PracticeSession"("id") ON DELETE SET NULL, "userAnswer" JSONB NOT NULL, "isCorrect" BOOLEAN NOT NULL, "errorType" TEXT, "aiFeedback" TEXT, "createdAt" TIMESTAMP(3) DEFAULT NOW());

CREATE TABLE IF NOT EXISTS "PracticeSession" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "projectId" TEXT NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE, "mode" TEXT NOT NULL DEFAULT 'point_practice', "status" TEXT DEFAULT 'in_progress', "totalQuestions" INTEGER NOT NULL, "correctCount" INTEGER, "resultJson" JSONB, "startedAt" TIMESTAMP(3) DEFAULT NOW(), "endedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) DEFAULT NOW());

CREATE TABLE IF NOT EXISTS "WrongQuestion" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "userId" TEXT NOT NULL REFERENCES "User"("id"), "projectId" TEXT NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE, "questionId" TEXT NOT NULL REFERENCES "PracticeQuestion"("id"), "attemptId" TEXT UNIQUE NOT NULL REFERENCES "QuestionAttempt"("id") ON DELETE CASCADE, "errorReason" TEXT, "recommendedAction" TEXT, "status" TEXT DEFAULT 'active', "resolvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) DEFAULT NOW());

CREATE TABLE IF NOT EXISTS "DiagnosticRun" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "projectId" TEXT NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE, "title" TEXT DEFAULT '摸底诊断', "status" TEXT DEFAULT 'generated', "generatedFrom" TEXT DEFAULT 'generic_subject_based', "totalQuestions" INTEGER NOT NULL, "correctCount" INTEGER NOT NULL DEFAULT 0, "predictedMin" INTEGER, "predictedMax" INTEGER, "paperSnapshot" JSONB, "answerSnapshot" JSONB, "gradingSnapshot" JSONB, "weakOpportunities" JSONB, "riskReport" JSONB, "createdAt" TIMESTAMP(3) DEFAULT NOW());

CREATE TABLE IF NOT EXISTS "SprintPlan" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "projectId" TEXT UNIQUE NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE, "version" INTEGER DEFAULT 1, "planType" TEXT DEFAULT 'pass_60', "targetTier" TEXT NOT NULL, "totalDays" INTEGER NOT NULL, "dailyMinutes" INTEGER NOT NULL DEFAULT 60, "status" TEXT DEFAULT 'active', "strategySummary" JSONB, "startScore" INTEGER, "targetScore" INTEGER NOT NULL, "latestPredScore" INTEGER, "createdAt" TIMESTAMP(3) DEFAULT NOW(), "updatedAt" TIMESTAMP(3) DEFAULT NOW());

CREATE TABLE IF NOT EXISTS "StudyTask" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "projectId" TEXT NOT NULL, "planId" TEXT NOT NULL REFERENCES "SprintPlan"("id") ON DELETE CASCADE, "examPointId" TEXT REFERENCES "ExamPoint"("id"), "moduleId" TEXT, "dayIndex" INTEGER DEFAULT 1, "title" TEXT NOT NULL, "taskType" TEXT NOT NULL DEFAULT 'learn', "priority" INTEGER DEFAULT 3, "estimatedMinutes" INTEGER NOT NULL, "expectedGain" DOUBLE PRECISION, "status" TEXT DEFAULT 'todo', "sourceReason" TEXT, "planVersion" INTEGER DEFAULT 1, "isLocked" BOOLEAN DEFAULT false, "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) DEFAULT NOW());

CREATE TABLE IF NOT EXISTS "AiTask" ("id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text, "projectId" TEXT NOT NULL REFERENCES "Project"("id") ON DELETE CASCADE, "materialId" TEXT REFERENCES "Material"("id"), "type" TEXT NOT NULL, "idempotencyKey" TEXT, "status" TEXT DEFAULT 'pending', "inputJson" JSONB, "outputJson" JSONB, "errorMessage" TEXT, "retryCount" INTEGER DEFAULT 0, "createdAt" TIMESTAMP(3) DEFAULT NOW(), "updatedAt" TIMESTAMP(3) DEFAULT NOW());
