var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/english/writing/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0uwwjx7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0tej5c5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0tor_u1.js")
R.c("server/chunks/ssr/[root-of-the-server]__10ldt1g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0r5yz5t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_app_english_loading_tsx_19empkd._.js")
R.c("server/chunks/ssr/_next-internal_server_app_english_writing_page_actions_0x0e6aj.js")
R.m(18453)
module.exports=R.m(18453).exports
