var R=require("../../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(app)/projects/[projectId]/diagnostic/report/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fw_6hj._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0tej5c5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_19jnlg5.js")
R.c("server/chunks/ssr/[root-of-the-server]__10ldt1g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0r5yz5t._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/src_app_(app)_layout_tsx_0olbgkk._.js")
R.c("server/chunks/ssr/1oeh_server_app_(app)_projects_[projectId]_diagnostic_report_page_actions_1w7kpiy.js")
R.m(30740)
module.exports=R.m(30740).exports
