// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(app)/projects/[projectId]/analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/analysis">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[projectId]/analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[projectId]/diagnostic/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/diagnostic/report">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[projectId]/diagnostic/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[projectId]/diagnostic/take/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/diagnostic/take">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[projectId]/diagnostic/take/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[projectId]/errors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/errors">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[projectId]/errors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[projectId]/exam/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/exam">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[projectId]/exam/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[projectId]/materials/[materialId]/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/materials/[materialId]/review">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[projectId]/materials/[materialId]/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[projectId]/materials/upload/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/materials/upload">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[projectId]/materials/upload/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[projectId]/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/overview">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[projectId]/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[projectId]/plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/plan">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[projectId]/plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[projectId]/points/[pointId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/points/[pointId]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[projectId]/points/[pointId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[projectId]/points/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/points">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[projectId]/points/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/[projectId]/practice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/practice">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/[projectId]/practice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/new">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/cloze/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english/cloze">> = Specific
  const handler = {} as typeof import("../../src/app/english/cloze/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/exam/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english/exam">> = Specific
  const handler = {} as typeof import("../../src/app/english/exam/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english/history">> = Specific
  const handler = {} as typeof import("../../src/app/english/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/listening/[testId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english/listening/[testId]">> = Specific
  const handler = {} as typeof import("../../src/app/english/listening/[testId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/listening/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english/listening">> = Specific
  const handler = {} as typeof import("../../src/app/english/listening/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/listening/result/[testId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english/listening/result/[testId]">> = Specific
  const handler = {} as typeof import("../../src/app/english/listening/result/[testId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/matching/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english/matching">> = Specific
  const handler = {} as typeof import("../../src/app/english/matching/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english">> = Specific
  const handler = {} as typeof import("../../src/app/english/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/reading/[articleId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english/reading/[articleId]">> = Specific
  const handler = {} as typeof import("../../src/app/english/reading/[articleId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/reading/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english/reading">> = Specific
  const handler = {} as typeof import("../../src/app/english/reading/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/real-exams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english/real-exams">> = Specific
  const handler = {} as typeof import("../../src/app/english/real-exams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/translation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english/translation">> = Specific
  const handler = {} as typeof import("../../src/app/english/translation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/vocab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english/vocab">> = Specific
  const handler = {} as typeof import("../../src/app/english/vocab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/english/writing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/english/writing">> = Specific
  const handler = {} as typeof import("../../src/app/english/writing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/subjects/[subject]/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subjects/[subject]/[section]">> = Specific
  const handler = {} as typeof import("../../src/app/subjects/[subject]/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/subjects/[subject]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subjects/[subject]">> = Specific
  const handler = {} as typeof import("../../src/app/subjects/[subject]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/subjects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subjects">> = Specific
  const handler = {} as typeof import("../../src/app/subjects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/articles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/articles/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/articles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/articles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/articles">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/articles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/cloze/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/cloze/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/cloze/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/exam/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/exam/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/exam/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/exam/score/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/exam/score">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/exam/score/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/import-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/import-link">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/import-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/listening/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/listening">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/listening/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/listening/sets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/listening/sets">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/listening/sets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/reading/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/reading/analyze">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/reading/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/reading/explain/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/reading/explain">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/reading/explain/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/reading/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/reading/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/reading/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/reading/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/reading/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/reading/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/refresh">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/word-definition/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/word-definition">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/word-definition/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/english/writing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/english/writing">> = Specific
  const handler = {} as typeof import("../../src/app/api/english/writing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/materials/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/materials/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/materials/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/diagnostic/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/diagnostic/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/diagnostic/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/diagnostic/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/diagnostic/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/diagnostic/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/errors/[errorId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/errors/[errorId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/errors/[errorId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/errors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/errors">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/errors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/exam-points/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/exam-points/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/exam-points/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/exam/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/exam/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/exam/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/exam/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/exam/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/exam/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/plan/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/plan/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/plan/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/plan/tasks/[taskId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/plan/tasks/[taskId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/plan/tasks/[taskId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/plan/today/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/plan/today">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/plan/today/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/practice/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/practice/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/practice/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/practice/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]/practice/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/practice/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
